services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_volume:/data/db
    command: mongod --logpath /dev/null  # Redirect logs to /dev/null
    ports:
      - 27018:27017

  redis:
    image: redis
    restart: always
    volumes:
      - redis_volume:/data
    ports:
      - 6380:6379

  api:
    image: portal-v2-api-dev
    container_name: api-service
    env_file:
      - .env.development
    build: .
    volumes:
      - .:/app
      - app_node_modules:/app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - mongo
      - redis
    restart: always
    environment:
      - MONGODB_URI=mongodb://root:example@mongo:27017/portal-v2?authSource=admin
      - REDIS_URI=redis://redis:6379

volumes:
  mongo_volume: {}
  redis_volume: {}
  app_node_modules: {}
